/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'items' : Array<CartItem> }
export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export interface Category { 'id' : CategoryId, 'name' : string }
export type CategoryId = bigint;
export interface Coupon {
  'code' : CouponCode,
  'discountPercentage' : bigint,
  'validUntil' : Time,
}
export type CouponCode = string;
export type Filter = { 'sortByCategory' : Order } |
  { 'page' : bigint } |
  { 'pageSize' : bigint } |
  { 'sortByName' : Order } |
  { 'maxPrice' : bigint } |
  { 'searchText' : string } |
  { 'sortByPrice' : Order } |
  { 'category' : CategoryId } |
  { 'minPrice' : bigint };
export type Order = { 'less' : null } |
  { 'equal' : null } |
  { 'greater' : null };
export type OrderId = bigint;
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null } |
  { 'processing' : null };
export interface Order__1 {
  'id' : OrderId,
  'status' : OrderStatus,
  'userId' : UserId,
  'statusHistory' : Array<OrderStatus>,
  'totalAmount' : bigint,
  'timestamp' : Time,
  'shippingAddress' : ShippingAddress,
  'items' : Array<CartItem>,
}
export interface Product {
  'id' : ProductId,
  'categoryId' : CategoryId,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'price' : bigint,
}
export type ProductId = bigint;
export type ReferralCode = string;
export interface ShippingAddress {
  'name' : string,
  'address' : string,
  'phone' : string,
  'pincode' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SiteSettings { 'logo' : string, 'shopName' : string }
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile { 'name' : string, 'address' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wishlist { 'productIds' : Array<ProductId> }
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[Category], CategoryId>,
  'addCoupon' : ActorMethod<[Coupon], undefined>,
  'addProduct' : ActorMethod<[Product], ProductId>,
  /**
   * / ************
   * /    * Cart & Wishlist
   * /    *************
   */
  'addToCart' : ActorMethod<[ProductId], undefined>,
  'addToWishlist' : ActorMethod<[ProductId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createReferral' : ActorMethod<[ReferralCode], undefined>,
  'deleteCategory' : ActorMethod<[CategoryId], undefined>,
  'deleteCoupon' : ActorMethod<[CouponCode], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  /**
   * / ************
   * /    * Coupons
   * /    *************
   */
  'getAllCoupons' : ActorMethod<[], Array<Coupon>>,
  'getAllCustomerOrders' : ActorMethod<[UserId], Array<Order__1>>,
  'getAllOrders' : ActorMethod<[], Array<Order__1>>,
  /**
   * / ************
   * /    * User Profile
   * /    *************
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getOrder' : ActorMethod<[OrderId], Order__1>,
  /**
   * / ************
   * /    * Products & Categories
   * /    *************
   */
  'getProducts' : ActorMethod<[Array<Filter>], Array<Product>>,
  /**
   * / ************
   * /    * Site Settings
   * /    *************
   */
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / ************
   * /    * Referrals & Orders
   * /    *************
   */
  'getUserReferrals' : ActorMethod<[UserId], Array<UserId>>,
  'getWishlist' : ActorMethod<[], Wishlist>,
  /**
   * / ************
   * /    * General
   * /    *************
   */
  'healthCheck' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  /**
   * / ************
   * /    * Place Order
   * /    *************
   */
  'placeOrder' : ActorMethod<[ShippingAddress], OrderId>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'removeFromWishlist' : ActorMethod<[ProductId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCategory' : ActorMethod<[CategoryId, Category], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[ProductId, Product], undefined>,
  'updateSiteSettings' : ActorMethod<[SiteSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];