/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CategoryId = IDL.Nat;
export const Category = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'image' : IDL.Text,
});
export const CouponCode = IDL.Text;
export const Time = IDL.Int;
export const Coupon = IDL.Record({
  'code' : CouponCode,
  'discountPercentage' : IDL.Nat,
  'validUntil' : Time,
});
export const ProductInput = IDL.Record({
  'categoryId' : CategoryId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});
export const ProductId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ReferralCode = IDL.Text;
export const UserId = IDL.Principal;
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
  'processing' : IDL.Null,
});
export const ShippingAddress = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const Order__1 = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'userId' : UserId,
  'statusHistory' : IDL.Vec(OrderStatus),
  'totalAmount' : IDL.Nat,
  'timestamp' : Time,
  'shippingAddress' : ShippingAddress,
  'items' : IDL.Vec(CartItem),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
});
export const Cart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
export const Product = IDL.Record({
  'id' : ProductId,
  'categoryId' : CategoryId,
  'owner' : UserId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});
export const Order = IDL.Variant({
  'less' : IDL.Null,
  'equal' : IDL.Null,
  'greater' : IDL.Null,
});
export const Filter = IDL.Variant({
  'sortByCategory' : Order,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'sortByName' : Order,
  'maxPrice' : IDL.Nat,
  'searchText' : IDL.Text,
  'sortByPrice' : Order,
  'category' : CategoryId,
  'minPrice' : IDL.Nat,
});
export const SiteSettings = IDL.Record({
  'logo' : IDL.Text,
  'shopName' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Wishlist = IDL.Record({ 'productIds' : IDL.Vec(ProductId) });
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([Category], [CategoryId], []),
  'addCoupon' : IDL.Func([Coupon], [], []),
  'addProduct' : IDL.Func([ProductInput], [ProductId], []),
  'addToCart' : IDL.Func([ProductId], [], []),
  'addToWishlist' : IDL.Func([ProductId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createReferral' : IDL.Func([ReferralCode], [], []),
  'deleteCategory' : IDL.Func([CategoryId], [], []),
  'deleteCoupon' : IDL.Func([CouponCode], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAllCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'getAllCustomerOrders' : IDL.Func([UserId], [IDL.Vec(Order__1)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order__1)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getOrder' : IDL.Func([OrderId], [Order__1], ['query']),
  'getOwnerProducts' : IDL.Func([IDL.Principal], [IDL.Vec(Product)], ['query']),
  'getProductOwner' : IDL.Func([ProductId], [IDL.Principal], ['query']),
  'getProducts' : IDL.Func([IDL.Vec(Filter)], [IDL.Vec(Product)], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserReferrals' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getWishlist' : IDL.Func([], [Wishlist], ['query']),
  'healthCheck' : IDL.Func([], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([ShippingAddress], [OrderId], []),
  'removeFromCart' : IDL.Func([ProductId], [], []),
  'removeFromWishlist' : IDL.Func([ProductId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCategory' : IDL.Func([CategoryId, Category], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [], []),
  'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CategoryId = IDL.Nat;
  const Category = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'image' : IDL.Text,
  });
  const CouponCode = IDL.Text;
  const Time = IDL.Int;
  const Coupon = IDL.Record({
    'code' : CouponCode,
    'discountPercentage' : IDL.Nat,
    'validUntil' : Time,
  });
  const ProductInput = IDL.Record({
    'categoryId' : CategoryId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ProductId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ReferralCode = IDL.Text;
  const UserId = IDL.Principal;
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
    'processing' : IDL.Null,
  });
  const ShippingAddress = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const Order__1 = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'userId' : UserId,
    'statusHistory' : IDL.Vec(OrderStatus),
    'totalAmount' : IDL.Nat,
    'timestamp' : Time,
    'shippingAddress' : ShippingAddress,
    'items' : IDL.Vec(CartItem),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'address' : IDL.Text });
  const Cart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
  const Product = IDL.Record({
    'id' : ProductId,
    'categoryId' : CategoryId,
    'owner' : UserId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Order = IDL.Variant({
    'less' : IDL.Null,
    'equal' : IDL.Null,
    'greater' : IDL.Null,
  });
  const Filter = IDL.Variant({
    'sortByCategory' : Order,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'sortByName' : Order,
    'maxPrice' : IDL.Nat,
    'searchText' : IDL.Text,
    'sortByPrice' : Order,
    'category' : CategoryId,
    'minPrice' : IDL.Nat,
  });
  const SiteSettings = IDL.Record({ 'logo' : IDL.Text, 'shopName' : IDL.Text });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Wishlist = IDL.Record({ 'productIds' : IDL.Vec(ProductId) });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([Category], [CategoryId], []),
    'addCoupon' : IDL.Func([Coupon], [], []),
    'addProduct' : IDL.Func([ProductInput], [ProductId], []),
    'addToCart' : IDL.Func([ProductId], [], []),
    'addToWishlist' : IDL.Func([ProductId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createReferral' : IDL.Func([ReferralCode], [], []),
    'deleteCategory' : IDL.Func([CategoryId], [], []),
    'deleteCoupon' : IDL.Func([CouponCode], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAllCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'getAllCustomerOrders' : IDL.Func([UserId], [IDL.Vec(Order__1)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order__1)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getOrder' : IDL.Func([OrderId], [Order__1], ['query']),
    'getOwnerProducts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductOwner' : IDL.Func([ProductId], [IDL.Principal], ['query']),
    'getProducts' : IDL.Func([IDL.Vec(Filter)], [IDL.Vec(Product)], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserReferrals' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getWishlist' : IDL.Func([], [Wishlist], ['query']),
    'healthCheck' : IDL.Func([], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([ShippingAddress], [OrderId], []),
    'removeFromCart' : IDL.Func([ProductId], [], []),
    'removeFromWishlist' : IDL.Func([ProductId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCategory' : IDL.Func([CategoryId, Category], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateProduct' : IDL.Func([ProductId, ProductInput], [], []),
    'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };